/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Coffeeshop } from "./Coffeeshop";
import { CoffeeshopCountArgs } from "./CoffeeshopCountArgs";
import { CoffeeshopFindManyArgs } from "./CoffeeshopFindManyArgs";
import { CoffeeshopFindUniqueArgs } from "./CoffeeshopFindUniqueArgs";
import { CreateCoffeeshopArgs } from "./CreateCoffeeshopArgs";
import { UpdateCoffeeshopArgs } from "./UpdateCoffeeshopArgs";
import { DeleteCoffeeshopArgs } from "./DeleteCoffeeshopArgs";
import { AdminFindManyArgs } from "../../admin/base/AdminFindManyArgs";
import { Admin } from "../../admin/base/Admin";
import { RewardFindManyArgs } from "../../reward/base/RewardFindManyArgs";
import { Reward } from "../../reward/base/Reward";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { CoffeeshopService } from "../coffeeshop.service";
@graphql.Resolver(() => Coffeeshop)
export class CoffeeshopResolverBase {
  constructor(protected readonly service: CoffeeshopService) {}

  async _coffeeshopsMeta(
    @graphql.Args() args: CoffeeshopCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Coffeeshop])
  async coffeeshops(
    @graphql.Args() args: CoffeeshopFindManyArgs
  ): Promise<Coffeeshop[]> {
    return this.service.coffeeshops(args);
  }

  @graphql.Query(() => Coffeeshop, { nullable: true })
  async coffeeshop(
    @graphql.Args() args: CoffeeshopFindUniqueArgs
  ): Promise<Coffeeshop | null> {
    const result = await this.service.coffeeshop(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Coffeeshop)
  async createCoffeeshop(
    @graphql.Args() args: CreateCoffeeshopArgs
  ): Promise<Coffeeshop> {
    return await this.service.createCoffeeshop({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Coffeeshop)
  async updateCoffeeshop(
    @graphql.Args() args: UpdateCoffeeshopArgs
  ): Promise<Coffeeshop | null> {
    try {
      return await this.service.updateCoffeeshop({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Coffeeshop)
  async deleteCoffeeshop(
    @graphql.Args() args: DeleteCoffeeshopArgs
  ): Promise<Coffeeshop | null> {
    try {
      return await this.service.deleteCoffeeshop(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Admin], { name: "admins" })
  async findAdmins(
    @graphql.Parent() parent: Coffeeshop,
    @graphql.Args() args: AdminFindManyArgs
  ): Promise<Admin[]> {
    const results = await this.service.findAdmins(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Reward], { name: "rewards" })
  async findRewards(
    @graphql.Parent() parent: Coffeeshop,
    @graphql.Args() args: RewardFindManyArgs
  ): Promise<Reward[]> {
    const results = await this.service.findRewards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: Coffeeshop,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
