/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AchievementService } from "../achievement.service";
import { AchievementCreateInput } from "./AchievementCreateInput";
import { Achievement } from "./Achievement";
import { AchievementFindManyArgs } from "./AchievementFindManyArgs";
import { AchievementWhereUniqueInput } from "./AchievementWhereUniqueInput";
import { AchievementUpdateInput } from "./AchievementUpdateInput";

export class AchievementControllerBase {
  constructor(protected readonly service: AchievementService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Achievement })
  async createAchievement(
    @common.Body() data: AchievementCreateInput
  ): Promise<Achievement> {
    return await this.service.createAchievement({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        pointsThreshold: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Achievement] })
  @ApiNestedQuery(AchievementFindManyArgs)
  async achievements(@common.Req() request: Request): Promise<Achievement[]> {
    const args = plainToClass(AchievementFindManyArgs, request.query);
    return this.service.achievements({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        pointsThreshold: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Achievement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async achievement(
    @common.Param() params: AchievementWhereUniqueInput
  ): Promise<Achievement | null> {
    const result = await this.service.achievement({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        pointsThreshold: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Achievement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAchievement(
    @common.Param() params: AchievementWhereUniqueInput,
    @common.Body() data: AchievementUpdateInput
  ): Promise<Achievement | null> {
    try {
      return await this.service.updateAchievement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          pointsThreshold: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Achievement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAchievement(
    @common.Param() params: AchievementWhereUniqueInput
  ): Promise<Achievement | null> {
    try {
      return await this.service.deleteAchievement({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          pointsThreshold: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
